<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MenuFormulesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuFormulesRepository extends EntityRepository
{
    public function findAllOrderedByNameAndByPrice()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM AppBundle:MenuFormules p ORDER BY p.menutypeId ASC, p.price'
            )
            ->getResult();
    }
}
